machine:
  python:
    version: 2.7.13
  post:
    - pyenv global 2.7.13

dependencies:
  pre:
    - pip -q install --upgrade pip
    - pip -q install PyYAML mkdocs pyembed-markdown

test:
  pre:
    - make docs

workflows:
  version: 2
  build_branch:
    jobs:
      - build_centos7

jobs:
  build_centos7:
    docker:
      - image: offical2600hz/php-packager-72:1.0-centos-7
        user: circleci
    steps:
    - checkout
    - run:
        name: Build message
        command: |
          echo "Build message"
