---
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/docs-user-guides

    steps:
      - run:
          command: pip install --user PyYAML mkdocs pyembed-markdown
      - run:
          command: make docs
