---
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - run:
          command: |
            pip -q install --upgrade pip
            pip -q install PyYAML mkdocs pyembed-markdown
      - run:
          command: |
            make docs
