site_name: Product Documentation

pages:
- 'index.md'
- 'Onboarding':
  - 'doc/onboarding/README.md'
  - 'MonsterUI':
    - 'Accessing Your Account': 'doc/onboarding/monster_ui/accessing_your_account.md'
    - 'Adding Apps': 'doc/onboarding/monster_ui/adding_apps.md'
    - 'Add Main Number': 'doc/onboarding/monster_ui/main_number.md'
    - 'Add Credit Card': 'doc/onboarding/monster_ui/credit_card.md'
    - 'Add Trunks': 'doc/onboarding/monster_ui/trunking.md'
  - 'First Office Setup':
    - 'doc/onboarding/first_office/README.md'
- 'Branding':
  - 'doc/branding/README.md'
  - 'doc/branding/branding_intro.md'
  - 'doc/branding/requirements.md'
- 'Carriers':
  - 'doc/carriers/README.md'
- 'Conferences':
  - 'doc/conferences/README.md'
  - 'doc/conferences/overview.md'
- 'Faxing':
  - 'doc/faxing/README.md'
  - 'SmartPBX Faxboxes': 'doc/faxing/smartpbx_faxbox.md'
  - 'Notifications': 'doc/faxing/fax_event_notifications.md'
- 'Mobile':
  - 'doc/mobile/README.md'
- 'Number Management':
  - 'doc/numbers/README.md'
  - 'Overview': 'doc/numbers/overview.md'
  - 'Blacklisting/Blocking': 'doc/numbers/number_blocking.md'
- 'PBXes':
  - 'doc/pbxes/README.md'
- 'Porting':
  - 'doc/porting/README.md'
  - 'doc/porting/overview.md'
  - 'doc/porting/submit-port-request.md'
  - 'doc/porting/monitor-port-request.md'
- 'Provisioner':
  - 'doc/provisioner/prov_start_guide.md'
  - 'Configuring Failover': 'doc/provisioner/failover/failover.md'
  - 'Configuring GeoIP': 'doc/provisioner/geoip/geoip.md'
  - 'Security': 'doc/provisioner/security/security.md'
  - 'Debugging':
    - 'Checking IP': 'doc/provisioner/debug/ip_check.md'
    - 'View Logs and Config Files': 'doc/provisioner/debug/logs_config_files.md'
  - 'Phones':
    - 'Cisco':
      - 'doc/provisioner/cisco/cisco_provisioning_guide.md'
    - 'Grandstream':
      - 'GXP 21xx': 'doc/provisioner/grandstream/gxp21xx_provisioning_guide.md'
    - 'Htek':
      - 'UC9xx': 'doc/provisioner/htek/htek_provisioning_guide.md'
    - 'Obihai':
      - 'doc/provisioner/obihai/obihai_provisioning_guide.md'
    - 'Polycom':
      - 'doc/provisioner/polycom/polycom_provisioning_guide.md'
    - 'Softphones':
      - 'Zoiper': 'doc/manual_phone_config/zoiper.md'
    - 'Yealink':
      - 'doc/provisioner/yealink/yealink_provisioning_guide.md'
- 'Whitelabel':
  - 'doc/whitelabel/README.md'
