site_name: Product Documentation
theme_dir: 2600Hz_theme

markdown_extensions:
  - pyembed.markdown

pages:
- 'index.md'
- 'Onboarding':
  - 'doc/onboarding/README.md'
  - 'MonsterUI':
    - 'Accessing Your Account': 'doc/onboarding/monster_ui/accessing_your_account.md'
    - 'Adding Apps': 'doc/onboarding/monster_ui/adding_apps.md'
    - 'Add Main Number': 'doc/onboarding/monster_ui/main_number.md'
    - 'Add Credit Card': 'doc/onboarding/monster_ui/credit_card.md'
    - 'Add Trunks': 'doc/onboarding/monster_ui/trunking.md'
  - 'First Office Setup':
    - 'doc/onboarding/first_office/README.md'
- 'Branding':
  - 'doc/branding/README.md'
- 'Carriers':
  - 'doc/carriers/README.md'
- 'Conferences':
  - 'doc/conferences/README.md'
- 'Faxing':
  - 'doc/faxing/README.md'
- 'Mobile':
  - 'doc/mobile/README.md'
- 'Numbers':
  - 'doc/numbers/overview.md'
- 'PBXes':
  - 'doc/pbxes/README.md'
- 'Porting':
  - 'doc/porting/README.md'
- 'Provisioner':
  - 'doc/provisioner/README.md'
  - 'Grandstream':
    - 'GXP 21xx': 'doc/provisioner/grandstream/gxp21xx_provisioning_guide.md'
  - 'Softphones':
    - 'Zoiper': 'doc/manual_phone_config/zoiper.md'
- 'Whitelabel':
  - 'doc/whitelabel/README.md'
